---
- name: Install Sublime Text on linux_machines
  hosts: linux_machines
  become: yes
  tasks:
    # Ensure apt cache is up-to-date
    - name: Update apt cache
      apt:
        update_cache: yes

    # Install Snapd if it's not already installed
    - name: Install snapd
      apt:
        name: snapd
        state: present

    # Install Sublime Text
    - name: Add Sublime Text GPG key
      apt_key:
        url: https://download.sublimetext.com/sublimehq-pub.gpg
        state: present

    - name: Add Sublime Text repository (stable channel)
      ansible.builtin.command:
        cmd: echo "deb https://download.sublimetext.com/ apt/stable/" | sudo tee /etc/apt/sources.list.d/sublime-text.list
      when: channel == "stable"

    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install Sublime Text
      apt:
        name: sublime-text
        state: present

    - name: Install Visual Studio Code from the stable channel using Snap
      snap:
        name: code
        state: present
        classic: yes  # Install with classic confinement
        channel: stable  # Specify the stable channel