---
- name: Install Obsidian and PyCharm on dev_group
  hosts: dev_group
  become: yes
  tasks:

    # Install Obsidian Snap package with --dangerous and --classic flags
    - name: Install Obsidian via Snap
      command: snap install obsidian --classic

    # Install PyCharm (Community Edition)
    - name: Download the PyCharm tarball
      get_url:
        url: "https://download.jetbrains.com/python/pycharm-community-2024.2.4.tar.gz"  # Replace this with the latest download link
        dest: "/tmp/pycharm.tar.gz"
        mode: '0644'

    - name: Download the PyCharm SHA256 checksum file
      get_url:
        url: "https://download.jetbrains.com/python/pycharm-community-2024.2.4.tar.gz.sha256"
        dest: "/tmp/pycharm.tar.gz.sha256"
        mode: '0644'

    - name: Read expected checksum from the .sha256 file
      command: "awk '{print $1}' /tmp/pycharm.tar.gz.sha256"
      register: expected_checksum
      changed_when: false

    - name: Calculate SHA256 checksum of the file
      stat:
        path: /tmp/pycharm.tar.gz
        checksum_algorithm: sha256
      register: file_stat

    - name: Assert that the checksum matches the expected value
      assert:
        that:
          - file_stat.stat.checksum == expected_checksum.stdout
        fail_msg: "Checksum does not match! The file may be corrupted."
        success_msg: "Checksum verified successfully!"

    - name: Unpack the PyCharm tarball to /opt
      unarchive:
        src: "/tmp/pycharm.tar.gz"
        dest: "/opt/"
        remote_src: yes

    - name: Find the PyCharm installation folder
      find:
        paths: "/opt"
        patterns: "pycharm-*"
        file_type: directory
      register: pycharm_folder

    - name: Ensure PyCharm was extracted successfully
      fail:
        msg: "PyCharm extraction failed!"
      when: pycharm_folder.matched == 0

    - name: Set the PyCharm bin directory path
      set_fact:
        pycharm_bin_path: "{{ pycharm_folder.files[0].path }}/bin"

    - name: Create a symbolic link to the PyCharm launcher script (optional)
      file:
        src: "{{ pycharm_bin_path }}/pycharm.sh"
        dest: "/usr/local/bin/pycharm"
        state: link
        mode: '0755'

    # Install spotify
    - name: Install Spotify using Snap
      snap:
        name: spotify
        state: present

    # Install Discord
    - name: Install Discord using Snap
      snap:
        name: discord
        state: present

    # Install wireguard
    - name: Install WireGuard using APT
      apt:
        name: wireguard
        state: present
        update_cache: yes  # Update the APT package cache

# working