---
- name: Generate SSH keys and configure SSH
  hosts: linux_machines
  become: no
  vars:
    algorithm: "ed25519"
    key_length: 256
    ssh_dir: "{{ ansible_env.HOME }}/.ssh"
    ssh_key_file: "{{ ssh_dir }}/id_{{ algorithm }}_{{ ansible_hostname }}"
    ssh_config_file: "{{ ssh_dir }}/config"
  vars_prompt:
    - name: ssh_passphrase
      prompt: "Enter a passphrase for the SSH key"
      private: yes  # This masks the input

  tasks:
    - name: Ensure .ssh directory exists
      file:
        path: "{{ ssh_dir }}"
        state: directory
        mode: '0700'

    - name: generate SSH key "{{ssh_key_file}}"
      user:
        name: "{{ lookup('env', 'USER') }}"
        generate_ssh_key: yes
        ssh_key_type: "{{ algorithm }}"
        ssh_key_bits: "{{ key_length }}"
        ssh_key_file: "{{ssh_key_file}}"
        ssh_key_passphrase: "{{ssh_passphrase}}"
        force: no

    - name: Ensure SSH config file exists
      file:
        path: "{{ ssh_config_file }}"
        state: touch
        mode: '0644'

    - name: Add entry to SSH config to use key for all hosts
      lineinfile:
        path: "{{ ssh_config_file }}"
        line: |
          Host *
            IdentityFile {{ ssh_key_file }}
        create: yes
        state: present