---
- name: Manage specific dotfiles with stow and git
  hosts: localhost
  vars:
    dotfiles_dirs:
      - bash
      - git
      - i3
      - polybar
      - ranger
      - vim
  tasks:
    - name: Run stow --adopt for specific dotfiles
      command: "stow --adopt {{ item }}"
      args:
        chdir: "{{ playbook_dir }}/dotfiles"
      loop: "{{ dotfiles_dirs }}"
      register: stow_result
      ignore_errors: yes
      tags: stow

    - name: Restore any changes to specific dotfiles with git
      command: git restore "{{ item }}"
      args:
        chdir: "{{ playbook_dir }}/dotfiles"
      loop: "{{ dotfiles_dirs }}"
      when: stow_result is succeeded
      tags: git_restore

# stow --adopt * \ git restore .
# stow --adopt bash \ git restore bash